[LOGGING]
log_file_path = LOG_FILE/log_file_%%d-%%m-%%Y.log
debug_file_path = DEBUG_FILE/debug_file_%%d-%%m-%%Y.log
DEBUG_FLAG = TRUE
table_context_print = FALSE
python_code_print = FALSE
execution_output = FALSE

[APP VERSION]
APP_VERSION = "v2.2.5"

[DEV VERSION]
DEV_VERSION = "v1.1.5"
DEV_TIMESTAMP = "2024-02-29T12:00:00Z"
