#### DB CREDENTIALS for local development ## FUTURE IT WILL ENCRYPTED
DB_USERNAME=MSPV7BI
DB_PASSWORD=MSPV7BI
DB_PORT=1521
DB_HOST=192.168.100.7
SID_NAME=ORA11G

#### DB MV/VIEWS/TABLES FOR SCHEDULING ##
[BOT_NAMES]
# vg_sales_order=VG SALES GPT
# View_Bi_Sale_Order=SALES ORDER GPT
# view_bi_sale_contract=SALES CONTRACT GPT
# View_Bi_Sale_Invoice= SALES INVOICE GPT
VIEW_SALES_MATRIX=SALES GPT

### SCHDULAR FETCH INTERVAL ##
FETCH_INTERVAL_HOURS=8 hrs